export const GET_LIST_LEAGUE_INIT = "GET_LIST_LEAGUE_INIT";
export const GET_LIST_LEAGUE_SUCCESS = "GET_LIST_LEAGUE_SUCCESS";
export const GET_LIST_LEAGUE_ERROR = "GET_LIST_LEAGUE_ERROR";
export const LOADING_COMPLETE = "LOADING_COMPLETE";
export const ADD_ITEM_SELECTED = "ADD_ITEM_SELECTED";
export const LEAGUE_COMPLETE = "LEAGUE_COMPLETE";
export const ACTIVATED_EDIT = "ACTIVATED_EDIT";
export const DELETE_LEAGUE = "DELETE_LEAGUE";
